# .github/workflows/netlify.yml
name: Netlify Build
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.14.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0
      - name: Install dependencies
        run: npm install
        env:
          CI: false
      - name: Generate build
        run: npm run build
      - name: files
        run: ls -a && cd build && ls -a
        env:
          CI: false

      # ( Build to ./dist or other directory... )

      - name: Deploy to Netlify [SuiCxDe]
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: 'build'
          production-branch: master
          github-token: ${{ secrets.TOKEN_GITHUB }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
